### ISSUE TITLE
Cannot get page if there is a link to itself

### ISSUE THREAD

**Issue by ImSingee** [kjk/notionapi#21]
If there is a "Link to page" block on the page, and the page points to itself, something goes wrong.

1. Can't use DownloadPage to download the page content.
2. If using the ToMarkdown method in tomarkdown package, an endless loop will be caused.

I create a page for example: https://www.notion.so/singee/Test-15061913435e4d79a49daff515f2afe0

**Comment by kjk** [comment]
Thanks for the report, should be fixed.

**Comment by ImSingee** [comment]
Thanks! The `DownloadPage` worked now, but `ToMarkdown` won't generate blocks after the "Link to page" block.
