### ISSUE TITLE
no users when trying to resolve collection_view

### ISSUE THREAD

**Issue by caarlos0** [kjk/notionapi#29]
notion did a maintenance yesterday, and I think they changed something that broke the lib.

https://twitter.com/NotionStatus/status/1305691756353126400

my daily refresh now fails with this error:

https://github.com/caarlos0/carlosbecker.com/runs/1120562268?check_suite_focus=true

I don't know enough of the API to attempt a fix... but I could debug it to the check that's failing: [this one](https://github.com/kjk/notionapi/blob/master/client.go#L497)

Thanks for this lib BTW :) awesome work!

**Comment by caarlos0** [comment]
BTW: removing the if and passing a built user to the queryCollection method seems to resolve the issue... will work on a PR :)

**Comment by kjk** [comment]
Should be fixed by https://github.com/kjk/notionapi/commit/c95813fdf9a5e91b6b7845a50ee253024a07b021

**Comment by caarlos0** [comment]
thanks!
