### ISSUE TITLE
[add]Addition of event based updates to webpage from notion calendar

### ISSUE THREAD

**Issue by caramelmelmel** [kjk/notionapi#45]
hi @kjk can I contribute to the addition of such a feature to embed a notion calendar into the webpage?

**Comment by kjk** [comment]
Sure. Could you briefly describe your plan? I'm not sure I fully understand the feature.

**Comment by caramelmelmel** [comment]
1. Notion has an inline calendar feature
2. I intend to try and export this inline calendar feature to embed into the webpage as live calendar

**Comment by caramelmelmel** [comment]
Is this sufficient?

**Comment by caramelmelmel** [comment]
@kjk

**Comment by kjk** [comment]
Yes, makes sense
