### ISSUE TITLE
Write data to page API request

### ISSUE THREAD

**Issue by ymszzq** [kjk/notionapi#8]
Thank you so much for your contribution!!!

It is possible to have a wring to page API. The page is a database.

**Comment by kjk** [comment]
I'm sure it's possible, but I would need more information.

Can you sketch the API you would like the library to provide?

Is it just adding new data? Editing existing data?

Can you describe the use case for such functionality?

**Comment by ymszzq** [comment]
Thanks for quick reply.

It is just for add new data to page.

Right I have a full page table. I want to add one line to table. It is similar to the official chrome notio web cliper. 

I think it is easier to add to page instead of table.

**Comment by Penagwin** [comment]
https://github.com/jamalex/notion-py Should helpout? They seem to support both directions.

**Comment by ymszzq** [comment]
I am trying out, thanks

**Comment by nickdyar** [comment]
fyi @jamalex, in case you're not already aware. Seems like good collab opportunity for all.

**Comment by jamalex** [comment]
Hiya! Different languages (Python vs Go), but let me know if you have any questions about the API or how we did particular things in notion-py!

**Comment by GreenHatHG** [comment]
@ymszzq Hi! I have the same need, have you solved it by kjk/notionapi?

**Comment by zmj1368** [comment]
@ymszzq Sir, i have the same question , have you solved it by kjk/notionapi?
